version: '3.8'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: rtmp-server
    restart: unless-stopped
    ports:
      - "1935:1935"    # Porta RTMP (entrada das c√¢meras)
      - "8080:80"      # Porta HTTP para servir HLS
    volumes:
      - ./nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-rtmp/hls:/tmp/hls
      - ./nginx-rtmp/recordings:/tmp/recordings
    networks:
      - streaming

networks:
  streaming:
    driver: bridge
