version: '3.8'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: rtmp-server
    restart: unless-stopped
    ports:
      - "1935:1935"    # RTMP
      - "8080:80"      # HLS
    volumes:
      - ./nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-rtmp/hls:/tmp/hls

networks:
  default:
    name: streaming
